// Generates the CSS variables and the registry "tokens" item from tokens.json.
// Usage: npm run tokens
import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const source = JSON.parse(
  readFileSync(join(root, "registry/iq/tokens/tokens.json"), "utf8")
)

const vars = {}
for (const group of source.groups) {
  for (const token of group.tokens) vars[token.name] = token.value
}

// 1. registry/iq/styles/tokens.css — imported by the docs site.
const css = [
  "/* Generated by scripts/build-tokens.mjs from registry/iq/tokens/tokens.json. Do not edit. */",
  ":root {",
  "  color-scheme: dark;",
  ...source.groups.flatMap((group) => [
    `  /* ${group.name} */`,
    ...group.tokens.map((t) => `  --${t.name}: ${t.value};`),
  ]),
  "}",
  "",
].join("\n")

const cssPath = join(root, "registry/iq/styles/tokens.css")
mkdirSync(dirname(cssPath), { recursive: true })
writeFileSync(cssPath, css)

// 2. registry.json — the "tokens" item merges these into the consumer's :root.
// shadcn writes cssVars.light to :root; the IQ system is dark-only, so that is the only mode.
const registryPath = join(root, "registry.json")
const registry = JSON.parse(readFileSync(registryPath, "utf8"))
const item = registry.items.find((i) => i.name === "tokens")
if (!item) throw new Error('registry.json is missing the "tokens" item')
item.cssVars = { light: vars }
writeFileSync(registryPath, JSON.stringify(registry, null, 2) + "\n")

console.log(`✓ ${Object.keys(vars).length} tokens → tokens.css + registry.json`)
